version: '3.8'

services:
  vue-app:
    container_name: vue-app
    image: node:latest
    networks:
      - default
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
